django_test/apps/user/urls.py
from django.urls import path
from user.views import UserList, UserQuery

app_name = 'user'

urlpatterns = [
    # 用户列表展示
    path('list/', UserList.as_view(), name="user_list"),
    # 用户相关数据查询
    path('query/', UserQuery.as_view(), name="user_query"),
]


django_test/django_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 用户模块url路径配置
    path('user/', include("user.urls", namespace="user")),
]

django_test/apps/user/models.py
from django.db import models

# Create your models here.


# 用户信息表 tbl_user_info
class UserInfo(models.Model):
    username = models.CharField('用户名', max_length=30, null=True)  # 用户名
    age = models.IntegerField('年龄', null=True)  # 年龄
    sex = models.CharField('性别', max_length=1, null=True)  # 性别，男或女
    mobile = models.CharField('手机号码', max_length=30, null=True)  # 手机号码
    address = models.CharField('地址', max_length=150, null=True)  # 地址
    createtime = models.DateTimeField('创建时间', auto_now_add=True, null=True)  # 创建时间

    class Meta:
        app_label = 'user'
        db_table = 'tbl_user_info'
        verbose_name = '用户信息表'    # admin后台显示的名称
        verbose_name_plural = verbose_name

django_test/apps/user/views.py
from django.shortcuts import render
from django.views import View
from user.models import UserInfo
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

class UserList(View):
    """
    用户列表展示
    """
    def get(self, request):
        return render(request, 'user/user_list.html')


class UserQuery(View):
    """
    用户信息查询
    """

    def post(self, request):
        user_list = UserInfo.objects.get_queryset().order_by('id')
        data = dict()
        data_items = []
        for item in user_list:
            user_dict = {"username": item.username, "age": item.age, "sex": item.sex, "mobile": item.mobile,
                         "address": item.address}
            data_items.append(user_dict)
        data.__setitem__("data", data_items)
        data.__setitem__("code", 0)
        data.__setitem__("msg", "")
        data.__setitem__("count", len(user_list))
        return JsonResponse(data)

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(UserQuery, self).dispatch(*args, **kwargs)

django_test/templates/user/user_list.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>测试</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi"/>
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/xadmin.css">
    <script src="/static/js/jquery.min.js" charset="utf-8"></script>
    <script src="/static/js/jquery.cookie.js" charset="utf-8"></script>
    <script type="text/javascript" src="/static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
            <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
            <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body ">
                    <blockquote class="layui-elem-quote layui-text">
                    <span class="layui-breadcrumb">
                        <a href="/">首页</a>
                        <a>测试</a>
                        <a><cite>测试详情</cite></a>
                    </span>
                    </blockquote>

                    <form class="layui-form">
                        {% csrf_token %}
                        <div class="layui-form-item">
                            <div class="layui-col-sm6 layui-col-md4">
                                <div class="layui-card">
                                    <div class="layui-card-body" style="height: 250px">
                                        <div class="layui-form-item">
                                            <div class="layui-form-text">
                                                上传用户头像：
                                            </div>
                                        </div>
                                        <div class="layui-upload-drag" id="upload_sign_doc">
                                            <i class="layui-icon"></i>
                                            <p>点击上传用户头像，或将文件拖拽到此处</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="layui-col-sm6 layui-col-md8">
                                <div class="layui-card">
                                    <div class="layui-card-body" style="height: 250px">
                                        <table class="layui-table">
                                            <thead>
                                            <tr>
                                                <th colspan="4" align="center" style="background-color: #4ea9fb">
                                                    用户列表
                                                </th>
                                            </tr>
                                            <tr>
                                                <th width="60%">用户名</th>
                                                <th width="40%">操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                    <tr>
                                                        <td></td>
                                                        <td>
                                                                <button type="button"
                                                                        class="layui-btn layui-btn-normal"
                                                                        id="user_data">用户数据展示
                                                                </button>
                                                        </td>
                                                    </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['table'],
        function () {
            var table = layui.table

            $("#user_data").click(function(){
                layer.open({
                        type: 1,
                        title: '用户信息',
                        area: ['800px', '600px'], //宽高
                        content: '<div class="layui-card-header"><div class="layui-form-text">用户信息列表</div>' +
                        '</div><div class="layui-form-item">' +
                        '<table id="user_table" lay-filter="user_table"></table></div>',
                        success: function () {
                            table.render({
                                elem: '#user_table',
                                id: 'user_table',
                                height: 480,
                                method: 'post', //接口http请求类型，默认：get
                                url: '{% url 'user:user_query' %}',
                                request: {
                                    pageName: 'page', //页码的参数名称，默认：page
                                    limitName: 'limit', //每页数据量的参数名，默认：limit
                                },
                                response: {
                                    statusName: 'code', //规定数据状态的字段名称，默认：code
                                    statusCode: 0, //规定成功的状态码，默认：0
                                    msgName: 'msg', //规定状态信息的字段名称，默认：msg
                                    countName: 'count', //规定数据总数的字段名称，默认：count
                                    dataName: 'data', //规定数据列表的字段名称，默认：data
                                },
                                page: true, //是否分页
                                limit: 10, //每页显示的条数
                                limits: [10, 20, 30], //每页条数的选择项，默认：[10,20,30,40,50,60,70,80,90]。
                                cols: [
                                    [
                                        {
                                            field: 'username', //字段名
                                            title: '用户名', //标题
                                            width: 150,
                                            sort: true, //是否允许排序 默认：false
                                            fixed: 'left' //固定列
                                        }, {
                                        field: 'sex', //字段名
                                        title: '性别', //标题
                                        width: 100,
                                        sort: true //是否允许排序 默认：false
                                        //fixed: 'left' //固定列
                                    }, {
                                        field: 'age', //字段名
                                        title: '年龄', //标题
                                        width: 100,
                                        sort: true //是否允许排序 默认：false
                                        //fixed: 'left' //固定列
                                    }, {
                                        field: 'mobile', //字段名
                                        title: '手机', //标题
                                        width: 100,
                                        sort: true //是否允许排序 默认：false
                                        //fixed: 'left' //固定列
                                    }, {
                                        field: 'address', //字段名
                                        title: '地址', //标题
                                        width: 150,
                                        sort: true //是否允许排序 默认：false
                                        //fixed: 'left' //固定列
                                    },{
                                        field: '', //字段名
                                        title: '操作', //标题
                                        toolbar: '#bar'
                                    }
                                    ]
                                ],
                            });
                        },
                        cancel: function () {
                            layer.closeAll();
                        }
                    })
            });
        });

</script>

<script type="text/html" id="bar">
    <button class="layui-btn layui-btn-normal">查看</button>
    <button class="layui-btn layui-btn-normal">编辑</button>
</script>

</body>

</html>